### ISSUE TITLE
Where's the source?

### ISSUE THREAD

**Issue by sgjava** [nikitinprior/Cross_compiler_z80#1]
Maybe I'm missing the boat, but this is just a readme. Where's the source files to build?

**Comment by agn453** [comment]
Andrey Nikitin (the owner of this repository) is located in Russia.  Two years ago you might remember an invasion of Ukraine commenced that resulted in Internet restrictions for Russian citizens.  I have not heard from Andrey since then.  You may wish to contact Mark Ogden @ogdenpm (see his GitHub profile for a contact e-mail address).  I understand it was Mark that was tidying up the source-code prior to its release.

Tony

**Comment by nikitinprior** [comment]
In the repository, “Cross_compiler_z80” contains only the file README.md which describes how to compile programs from source codes to create a cross-compiler. The restored source codes themselves are located in separate repositories, namely:
The control program - https://github.com/nikitinprior/Control-program-Cross-compiler-z80
The preprocessor program - https://github.com/nikitinprior/dcpp
The program of the first pass - https://github.com/nikitinprior/dp1
Code generation program - https://github.com/nikitinprior/dcgenv2
Optimization program - https://github.com/nikitinprior/doptim
The macro assembler program - https://github.com/nikitinprior/dzas
The linker program - https://github.com/nikitinprior/dzas
Object File Viewer - https://github.com/nikitinprior/pobjtohex
The Librarian's program - https://github.com/nikitinprior/dlibr
The program for building cross-references - https://github.com/nikitinprior/dcref
Dump program - https://github.com/nikitinprior/ddump

All these programs allow you to create a full-fledged cross-compiler with a set of programs similar to the original version.

In addition, Mark Ogden independently created his own version of the preprocessor program - https://github.com/nikitinprior/Preprocessor-source-code .
This preprocessor uses other options when called from the command line.

From these restored source codes, I compiled a cross-compiler that runs the Mac OS operating system on a MacBook Pro computer with an M1 processor.

Andrey Nikitin

**Comment by sgjava** [comment]
OK, I tried the 4.11 HTC DOS cross compiler and it produced code that would hang. Just looking at alternatives as memory is always an issue with CP/M based v3.09.

**Comment by sgjava** [comment]
OK, I tried the 4.11 HTC DOS cross compiler and it produced code that would hang. Just looking at alternatives as memory is always an issue with CP/M based v3.09.

**Comment by ogdenpm** [comment]
All,
 I appreciate this issue is closed, but I have finally shared my build tree for all of the tools along with a Visual Studio solution file and Linux makefiles to a new repository
https://github.com/ogdenpm/hitech
Mark

**Comment by sgjava** [comment]
@ogdenpm it would be nice if there were a bash version of https://github.com/ogdenpm/hitech/blob/main/Scripts/install.cmd assuming it installs everything.

**Comment by ogdenpm** [comment]
Stephen
I didn’t produce a bash version as most Linux/unix systems come with an install program.
The Linux build does produce all its files in the Linux/Install directory so a simple cp should be viable if you don’t have install on your system.

Note I also didn’t include my install.cfg as it targets my computer. If you look in my versiontools repository on GitHub it includes an example install.cfg
Regards
Mark

Regards
Mark Ogden
________________________________

**Comment by sgjava** [comment]
I get it, I was just being lazy. I typically produce an install.sh like https://github.com/sgjava/install-zabbix/blob/master/scripts/install.sh because I know folks will not do something with more than 5 steps.

**Comment by ogdenpm** [comment]
Stephen
As a simple suggestion in the hi.mk include file modify the line which copies the file to the Install directly to your desired location. You may need sudo to get the permissions.

Regards
Mark Ogden
________________________________

**Comment by ogdenpm** [comment]
Stephen
In a separate issue what is the nature of the code that is failing with the 4.11 compiler.
Mark

Regards
Mark Ogden
________________________________

**Comment by sgjava** [comment]
https://github.com/agn453/HI-TECH-Z80-C/blob/master/test/TESTTRIG.C is one. It hangs after first print. You'll get tons of type mismatch because of stricter type checking. But also stuff that builds fine in 3.09 will fail in 4.11.

**Comment by ogdenpm** [comment]
Steven

The issue is a bug in fnum.c in the floating point library

Specifically in the handling of the ‘e’ format when val is 0.0

The original code has

    while(val < 1.0) {

                val *= 10.0;

                exp--;

    }

Which if val is 0.0 loops for ever

The fix is to check for val first

        if (val == 0.0)

            exp =0 ;

        else

            while(val < 1.0) {

                val *= 10.0;

                exp--;

            }

The setting of exp to 0 is optional, but makes things tidy.

Regards

Mark
